version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/a-hilaly/lab-grpc
    steps:
      - checkout

      - run:
          name: install protobuf & grpc
          command: |
            # protoc
            PROTOC_ZIP=protoc-3.6.1-linux-x86_64.zip
            curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/$PROTOC_ZIP
            sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
            rm -f $PROTOC_ZIP

            # grpc go plugin
            go get -u github.com/golang/protobuf/protoc-gen-go
            
      - run:
          name: compile protos
          command: |
            # Add go binaries folder to PATH 
            export PATH=$PATH:/go/bin

            # compile protos
            make compile-protos

      - run:
          name: build 
          command: |
            # install dependencies
            go mod tidy

            # build server
            make build-server
            make build-client

